// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3IV4tuGOg8afcneR0ljUCxNIlhExPHN8',
    appId: '1:282116274736:web:1729f4ba15b9b1993c4bf5',
    messagingSenderId: '282116274736',
    projectId: 'github-social-6c565',
    authDomain: 'github-social-6c565.firebaseapp.com',
    storageBucket: 'github-social-6c565.firebasestorage.app',
    measurementId: 'G-ZKNKK6TM3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn-9sSSAM9-bt2CqnNNuWJsOS6B-vR0VM',
    appId: '1:282116274736:android:af3c6795952a73e93c4bf5',
    messagingSenderId: '282116274736',
    projectId: 'github-social-6c565',
    storageBucket: 'github-social-6c565.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB0UjFCHtRZ4tdYE0YLIWJoY0JR2P9NcU',
    appId: '1:282116274736:ios:f4a13bb639d7e1f43c4bf5',
    messagingSenderId: '282116274736',
    projectId: 'github-social-6c565',
    storageBucket: 'github-social-6c565.firebasestorage.app',
    iosBundleId: 'com.example.githubSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB0UjFCHtRZ4tdYE0YLIWJoY0JR2P9NcU',
    appId: '1:282116274736:ios:f4a13bb639d7e1f43c4bf5',
    messagingSenderId: '282116274736',
    projectId: 'github-social-6c565',
    storageBucket: 'github-social-6c565.firebasestorage.app',
    iosBundleId: 'com.example.githubSocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3IV4tuGOg8afcneR0ljUCxNIlhExPHN8',
    appId: '1:282116274736:web:fff815237ddef4823c4bf5',
    messagingSenderId: '282116274736',
    projectId: 'github-social-6c565',
    authDomain: 'github-social-6c565.firebaseapp.com',
    storageBucket: 'github-social-6c565.firebasestorage.app',
    measurementId: 'G-9X9TZF6PX4',
  );
}
